
@host=http://localhost:4040

@authorization=IqGU93wulGWzpv7l9p7O8DzYfBarHEltSD0sXC3hmfHUmSfOYjq5IxlJb3tuyJy6

###
GET {{host}}/health

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
    "phone": "+573123749187"
}

###
POST {{host}}/auth/sign-up
Content-Type: application/json

{
  "name": "julio",
  "last_name": "torres",
  "phone": "+573013819315",
  "email": "jtorres990@gmail.com",
  "password": "Mastercard-1!"
}

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "jtorres990@gmail.com",
  "password": "Mastercard-1!"
}

###
GET {{host}}/auth/session
Authorization: Bearer {{authorization}}

###
POST {{host}}/auth/verification-code
Content-Type: application/json

{
    "phone": "+573123749187",
    "code": "DG6Trd"
}

###
GET {{host}}/auth/session
Content-Type: application/json
Authorization: Bearer {{authorization}}

###
GET {{host}}/connections
Authorization: Bearer {{authorization}}

###
POST {{host}}/mmlu/answer
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "bot_id": 1,
  "prompt": "tengo sed"
}

###
POST {{host}}/mmlu/embeddings
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "bot_id": 1,
  "prompt": "hello world"
}

###
GET {{host}}/mmlu/history/1
Authorization: Bearer {{authorization}}

###
DELETE {{host}}/mmlu/history/1
Authorization: Bearer {{authorization}}

###
POST http://localhost:11434/api/embeddings
Content-Type: application/json

{
  "prompt": "Hello world"
}